products_mapping = {
    "Id": "Id",
    "name": "name",
    "productType": "type",
    "company": "company",
    "applicableCountries": "applicableCountries.$oid",
    "applicableRegions": "applicableRegions.$oid",
    "applicationNutrientUnit": "applicationNutrientUnit",
    "applicationRateUnit": "applicationRateUnit",
    "brand": "brand",
    "dhcode": "dhcode",
    "nutrients": "nutrients",
    "originCountry": "originCountry",
    "reportName": "reportName",
    "density": "density",
    "images": "images",
    "createdBy": "createdBy.$oid",
    "createdAt": "createdAt.$date",
    "updatedBy": "updatedBy.$oid",
    "updatedAt": "updatedAt.$date",
    "deletedBy": "deletedBy.$oid",
    "deleteAt": "deletedAt.$date",
    "legacy": "legacy",
    "ec": "ec",
    "insertedViaUpdateTreatmentProductsMigration": "insertedViaUpdateTreatmentProductsMigration"
}
