--Inserting old records from old to new table----
insert into curated_schema.di_season(datetimeoccurred,
    sourcefile_name,
    sourcefile_receiveddate,
    sourceseasonid,
    sourcefieldid,
    seasonname,
    cropregionid,
    growthstageid,
    growthstagesystem,
    startdate,
    enddate,
    fieldsize,
    expectedyielddetails,
    additionalparameters,
    fieldsizeuomid,
    feature,
    center,
    geohash,
    geometryHash,
    eventid,
    eventsource,
    eventtype,
    created_at)
 select datetimeoccurred,
    sourcefile_name,
    sourcefile_receiveddate,
    sourceseasonid,
    sourcefieldid,
    seasonname,
    cropregionid,
    growthstageid,
    growthstagesystem,
    startdate,
    enddate,
    fieldsize,
    expectedyielddetails,
    additionalparameters,
    fieldsizeuomid,
    feature,
    center,
    geohash,
    geometryHash,
    eventid,
    eventsource,
    eventtype,
    created_at from curated_schema.di_season_old;
  
DROP table curated_schema.di_season_old;  