/******* polaris_ghg_performed DDL  (Green house gas calculator)********/

DROP TABLE IF EXISTS curated_schema.polaris_ghg_performed;

CREATE TABLE curated_schema.polaris_ghg_performed (
    datetimeoccurred timestamp without time zone NOT NULL ENCODE az64,
    request_location_countryid character varying(255) NOT NULL ENCODE lzo,
    request_location_regionid character varying(255) NOT NULL ENCODE lzo,
    request_field_fieldsize double precision NOT NULL ENCODE raw,
    request_field_fieldsizeunitid character varying(255) NOT NULL ENCODE lzo,
    request_field_soil_soiltypeid character varying(255) NOT NULL ENCODE lzo,
    request_field_soil_organicmatter double precision ENCODE raw,
    request_field_soil_gooddrainage boolean ENCODE raw,
    request_field_soil_ph double precision ENCODE raw,
    request_field_longitude double precision ENCODE raw,
    request_field_latitude double precision ENCODE raw,
    request_cropping_cropregionid character varying(255) NOT NULL ENCODE lzo,
    request_cropping_yield double precision NOT NULL ENCODE raw,
    request_cropping_yieldunitid character varying(255) NOT NULL ENCODE lzo,
    request_cropping_farmgatereadyamount double precision NOT NULL ENCODE raw,
    request_cropping_farmgatereadyamountunitid character varying(255) NOT NULL ENCODE lzo,
    request_cropping_harvestingyear double precision NOT NULL ENCODE raw,
    request_cropping_coproducts character varying(10000) ENCODE lzo,
    request_climate_name character varying(255) ENCODE lzo,
    request_climate_averagetemperaturevalue double precision ENCODE raw,
    request_climate_averagetemperaturevalueunitid character varying(255) ENCODE lzo,
    request_residues_amount double precision ENCODE raw,
    request_residues_amountunitid character varying(255) ENCODE lzo,
    request_residues_cropresiduemanagementid character varying(100) ENCODE lzo,
    request_appliedproducts character varying(10000) ENCODE lzo,
    request_wasteWaterOrganicMatter_wasteWaterAmount double precision ENCODE raw,
    request_wasteWaterOrganicMatter_wasteWaterAmountUnitId character varying(10000) ENCODE lzo,
    request_wasteWaterOrganicMatter_oxygenDemand double precision ENCODE raw,
    request_wasteWaterOrganicMatter_oxygenDemandUnitId character varying(10000) ENCODE lzo,
    request_wasteWaterOrganicMatter_oxygenDemandTypeName character varying(10000) ENCODE lzo,
    request_wasteWaterOrganicMatter_waterTreatmentTypeName character varying(10000) ENCODE lzo,
    request_applied_products_directenergyuse character varying(10000) ENCODE lzo,
    request_applied_products_machineryuse character varying(10000) ENCODE lzo,
    request_applied_products_transport character varying(10000) ENCODE lzo,
    request_irrigationEvents character varying(10000) ENCODE lzo,
    request_applied_products_cropprotectionapplications character varying(10000) ENCODE lzo,
    request_treeBiomass character varying(10000) ENCODE lzo,
    request_carbonChanges_carbonChanges character varying(10000) ENCODE lzo,
    response_success boolean NOT NULL ENCODE raw,
    response_message character varying(1000) ENCODE lzo,
    response_payload_summary_emissionsco2etotal double precision ENCODE raw,
    response_payload_summary_emissionsco2etotalunitid character varying(100)  ENCODE lzo,
    response_payload_summary_emissionsco2eperarea double precision ENCODE raw,
    response_payload_summary_emissionsco2eperareaunitid character varying(255)  ENCODE lzo,
    response_payload_summary_emissionsco2eperproduct double precision ENCODE raw,
    response_payload_summary_emissionsco2eperproductunitid character varying(255)  ENCODE lzo,
    response_payload_summary_soilorganiccarbon character varying(100) ENCODE lzo,
    response_payload_totalemissions character varying(10000) ENCODE lzo,
    configuration_solution character varying(100) ENCODE lzo,
    eventsource character varying(100) NOT NULL ENCODE lzo,
    eventtype character varying(100) NOT NULL ENCODE lzo,
    eventid character varying(255) NOT NULL ENCODE lzo,
    created_at character varying(255) NOT NULL ENCODE lzo
) DISTSTYLE AUTO;

GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE curated_schema.polaris_ghg_performed TO gluejob;