-- soil product recommendation v1 performed DDL script

DROP TABLE IF EXISTS curated_schema.polaris_soil_product_recommendation_v1_performed;

Create table curated_schema.polaris_soil_product_recommendation_v1_performed (
dateTimeOccurred TIMESTAMP WITHOUT TIME ZONE, 
request_location_CountryId varchar(100), 
request_location_RegionId varchar(100), 
request_field_Id varchar(100), 
request_field_Boundaries SUPER,
request_field_Size DOUBLE PRECISION,
request_field_SizeUnitId varchar(100),
request_field_SoilTypeId varchar(100),
request_cropping_CropId varchar(100),
request_cropping_Yield DOUBLE PRECISION,
request_cropping_YieldUnit varchar(100),
request_cropping_FarmId varchar(100),
request_cropping_FieldId varchar(100),
request_cropping_CroppableArea Double precision,
request_cropping_CroppableAreaUnit varchar(100),
request_cropping_AdditionalParameters SUPER,
request_cropping_CropResidueManagementId  varchar(100),
request_rotation_PreCropId varchar(100), 
request_rotation_PreCropYield DOUBLE PRECISION,
request_rotation_PreCropYieldUnit varchar(100),
request_rotation_PreCropResidueManagementId varchar(100),
request_rotation_PostCropId varchar(100), 
request_rotation_PostCropYield DOUBLE PRECISION,
request_rotation_PostCropYieldUnit varchar(100),
request_rotation_PostCropResidueManagementId varchar(100),
request_insight_Locale varchar(100), 
request_insight_IncludeInsights BOOLEAN,
request_analysis_classes_N varchar(100), 
request_analysis_classes_P varchar(100),
request_analysis_classes_K varchar(100), 
request_analysis_classes_S varchar(100), 
request_analysis_classes_Mg varchar(100), 
request_analysis_classes_Ca varchar(100), 
request_analysis_classes_B varchar(100),  
request_analysis_classes_Mo varchar(100), 
request_analysis_classes_Zn varchar(100), 
request_analysis_classes_Cu varchar(100),
request_analysis_classes_Fe varchar(100),  
request_analysis_classes_Mn varchar(100), 
request_analysis_classes_Na varchar(100), 
request_analysis_classes_Se varchar(100),  
request_analysis_classes_Co varchar(100), 
request_analysis_values_NMin DOUBLE PRECISION, 
request_analysis_values_SMin DOUBLE PRECISION, 
request_analysis_values_Clay DOUBLE PRECISION,
request_analysis_values_Sand DOUBLE PRECISION, 
request_analysis_values_Silt DOUBLE PRECISION,
request_analysis_values_Slit DOUBLE PRECISION,
request_analysis_values_SumOfBases DOUBLE PRECISION, 
request_analysis_values_EC DOUBLE PRECISION,
request_analysis_values_OrgM DOUBLE PRECISION, 
request_analysis_values_OrgC DOUBLE PRECISION,
request_analysis_values_CEC DOUBLE PRECISION, 
request_analysis_values_pH DOUBLE PRECISION, 
request_analysis_values_BpH DOUBLE PRECISION, 
request_analysis_values_BsSat DOUBLE PRECISION,
request_analysis_values_KSat DOUBLE PRECISION, 
request_analysis_values_MgSat DOUBLE PRECISION,
request_analysis_values_CaSat DOUBLE PRECISION, 
request_analysis_values_AlSat DOUBLE PRECISION,
request_analysis_values_NO3 DOUBLE PRECISION,  
request_analysis_values_NH4 DOUBLE PRECISION,
request_analysis_values_N DOUBLE PRECISION, 
request_analysis_values_P DOUBLE PRECISION, 
request_analysis_values_K DOUBLE PRECISION, 
request_analysis_values_S DOUBLE PRECISION, 
request_analysis_values_Mg DOUBLE PRECISION, 
request_analysis_values_Ca DOUBLE PRECISION,
request_analysis_values_Zn DOUBLE PRECISION, 
request_analysis_values_B DOUBLE PRECISION,
request_analysis_values_Mo DOUBLE PRECISION, 
request_analysis_values_Cu DOUBLE PRECISION, 
request_analysis_values_Fe DOUBLE PRECISION, 
request_analysis_values_Mn DOUBLE PRECISION,  
request_analysis_values_Al DOUBLE PRECISION, 
request_analysis_values_Na DOUBLE PRECISION, 
request_analysis_values_Se DOUBLE PRECISION, 
request_analysis_values_Co DOUBLE PRECISION, 
request_analysis_values_SMP DOUBLE PRECISION,
request_analysis_values_PRem DOUBLE PRECISION,  
request_demand_crop_N DOUBLE PRECISION,
request_demand_crop_P DOUBLE PRECISION, 
request_demand_crop_K DOUBLE PRECISION, 
request_demand_crop_S DOUBLE PRECISION, 
request_demand_crop_Mg DOUBLE PRECISION, 
request_demand_crop_Ca DOUBLE PRECISION,
request_demand_crop_B DOUBLE PRECISION, 
request_demand_crop_Mo DOUBLE PRECISION,
request_demand_crop_Zn DOUBLE PRECISION,
request_demand_crop_Cu DOUBLE PRECISION, 
request_demand_crop_Fe DOUBLE PRECISION, 
request_demand_crop_Mn DOUBLE PRECISION, 
request_demand_crop_Na DOUBLE PRECISION, 
request_demand_crop_Se DOUBLE PRECISION, 
request_demand_crop_Co DOUBLE PRECISION, 
request_demand_soil_N DOUBLE PRECISION, 
request_demand_soil_P DOUBLE PRECISION, 
request_demand_soil_K DOUBLE PRECISION,  
request_demand_soil_S DOUBLE PRECISION, 
request_demand_soil_Mg DOUBLE PRECISION,
request_demand_soil_Ca DOUBLE PRECISION, 
request_demand_soil_B DOUBLE PRECISION, 
request_demand_soil_Mo DOUBLE PRECISION,
request_demand_soil_Zn DOUBLE PRECISION,
request_demand_soil_Cu DOUBLE PRECISION, 
request_demand_soil_Fe DOUBLE PRECISION,  
request_demand_soil_Mn DOUBLE PRECISION,  
request_demand_soil_Na DOUBLE PRECISION,
request_demand_soil_Se DOUBLE PRECISION,
request_demand_soil_Co DOUBLE PRECISION,
request_demand_unit_N VARCHAR(100), 
request_demand_unit_P VARCHAR(100),
request_demand_unit_K VARCHAR(100),  
request_demand_unit_S VARCHAR(100), 
request_demand_unit_Mg VARCHAR(100), 
request_demand_unit_Ca VARCHAR(100),
request_demand_unit_B VARCHAR(100),
request_demand_unit_Mo VARCHAR(100), 
request_demand_unit_Zn VARCHAR(100), 
request_demand_unit_Cu VARCHAR(100),
request_demand_unit_Fe VARCHAR(100), 
request_demand_unit_Mn VARCHAR(100),  
request_demand_unit_Na VARCHAR(100), 
request_demand_unit_Se VARCHAR(100),  
request_demand_unit_Co VARCHAR(100), 
request_demand_unit_NUnitId VARCHAR(100), 
request_demand_unit_PUnitId VARCHAR(100), 
request_demand_unit_KUnitId VARCHAR(100),  
request_demand_unit_SUnitId VARCHAR(100), 
request_demand_unit_MgUnitId VARCHAR(100), 
request_demand_unit_CaUnitId VARCHAR(100), 
request_demand_unit_BUnitId VARCHAR(100),  
request_demand_unit_MoUnitId VARCHAR(100), 
request_demand_unit_ZnUnitId VARCHAR(100), 
request_demand_unit_CuUnitId VARCHAR(100), 
request_demand_unit_FeUnitId VARCHAR(100), 
request_demand_unit_MnUnitId VARCHAR(100), 
request_demand_unit_NaUnitId VARCHAR(100), 
request_demand_unit_SeUnitId VARCHAR(100), 
request_demand_unit_CoUnitId VARCHAR(100), 
request_demand_unit_Amount VARCHAR(100),   
request_UserDefinedProducts SUPER, 
request_UserAppliedProducts SUPER, 
request_config_RecommendAfterSplitApplication BOOLEAN,  
request_config_CheckCropChlorideSensitivity BOOLEAN, 
request_config_UseYaraPreferredProducts BOOLEAN, 
request_config_Capability VARCHAR(100),  
request_requestdetails_Id VARCHAR(100), 
request_requestdetails_Date VARCHAR(100),   
request_requestdetails_RulesetVersion VARCHAR(100), 
response_Success BOOLEAN, 
response_Begin VARCHAR(100), 
response_End VARCHAR(100), 
response_payload_yield_Items SUPER, 
response_payload_precropyield_Items SUPER,  
response_payload_postcropyield_Items SUPER, 
response_payload_demandunitdata_Items SUPER, 
response_payload_splitdata_Items SUPER, 
response_payload_Recommendationdata_Items SUPER, 
response_payload_organicsupply_Items SUPER, 
response_payload_cropdemand_Items SUPER, 
response_payload_soilimprovementdemand_Items SUPER, 
response_payload_fertilizerneed_Items SUPER, 
response_payload_config_Items SUPER, 
response_requestdetails_Id VARCHAR(100),  
response_requestdetails_Date VARCHAR(100), 
response_requestdetails_RulesetVersion VARCHAR(100),  
response_errordata_Errors SUPER, 
response_errordata_solution VARCHAR(100),  
eventSource  VARCHAR(100),  
eventType  VARCHAR(100),  
eventId  VARCHAR(100), 
created_at  VARCHAR(100)
);

GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE curated_schema.polaris_soil_product_recommendation_v1_performed TO gluejob;

GRANT SELECT ON TABLE curated_schema.polaris_soil_product_recommendation_v1_performed TO "IAM:ffdp-airflow";