DROP TABLE IF EXISTS ffdp2_0.polaris_ghg_performed;

CREATE TABLE IF NOT EXISTS ffdp2_0.polaris_ghg_performed
(
	datetimeoccurred TIMESTAMP WITHOUT TIME ZONE,
	request_location_countryid VARCHAR(255),
	request_location_regionid VARCHAR(255),
	request_field_fieldsize DOUBLE PRECISION,
	request_field_fieldsizeunitid VARCHAR(255),
	request_field_soil_soiltypeid VARCHAR(255),
	request_field_soil_organicmatter DOUBLE PRECISION,
	request_field_soil_gooddrainage BOOLEAN,
	request_field_soil_ph DOUBLE PRECISION,
	request_field_longitude DOUBLE PRECISION,
	request_field_latitude DOUBLE PRECISION,
	request_cropping_cropregionid VARCHAR(255),
	request_cropping_yield DOUBLE PRECISION,
	request_cropping_yieldunitid VARCHAR(255),
	request_cropping_farmgatereadyamount DOUBLE PRECISION,
	request_cropping_farmgatereadyamountunitid VARCHAR(255),
	request_cropping_harvestingyear DOUBLE PRECISION,
	request_cropping_coproducts VARCHAR(10000),
	request_climate_name VARCHAR(255),
	request_climate_averagetemperaturevalue DOUBLE PRECISION,
	request_climate_averagetemperaturevalueunitid VARCHAR(255),
	request_residues_amount DOUBLE PRECISION,
	request_residues_amountunitid VARCHAR(255),
	request_residues_cropresiduemanagementid VARCHAR(100),
	request_appliedproducts VARCHAR(10000),
	request_wastewaterorganicmatter_wastewateramount DOUBLE PRECISION,
	request_wastewaterorganicmatter_wastewateramountunitid VARCHAR(10000),
	request_wastewaterorganicmatter_oxygendemand DOUBLE PRECISION,
	request_wastewaterorganicmatter_oxygendemandunitid VARCHAR(10000),
	request_wastewaterorganicmatter_oxygendemandtypename VARCHAR(10000),
	request_wastewaterorganicmatter_watertreatmenttypename VARCHAR(10000),
	request_applied_products_directenergyuse VARCHAR(10000),
	request_applied_products_machineryuse VARCHAR(10000),
	request_applied_products_transport VARCHAR(10000),
	request_irrigationevents VARCHAR(10000),
	request_applied_products_cropprotectionapplications VARCHAR(10000),
	request_treebiomass VARCHAR(10000),
	request_carbonchanges_carbonchanges VARCHAR(10000),
	response_success BOOLEAN,
	response_message VARCHAR(1000),
	response_payload_summary_emissionsco2etotal DOUBLE PRECISION,
	response_payload_summary_emissionsco2etotalunitid VARCHAR(100),
	response_payload_summary_emissionsco2eperarea DOUBLE PRECISION,
	response_payload_summary_emissionsco2eperareaunitid VARCHAR(255),
	response_payload_summary_emissionsco2eperproduct DOUBLE PRECISION,
	response_payload_summary_emissionsco2eperproductunitid VARCHAR(255),
	response_payload_summary_soilorganiccarbon VARCHAR(100),
	response_payload_totalemissions VARCHAR(10000),
	configuration_solution VARCHAR(100),
	eventsource VARCHAR(100),
	eventtype VARCHAR(100),
	eventid VARCHAR(255),
	created_at VARCHAR(255)
);

-- polaris_n_uptake_performed
ALTER TABLE ffdp2_0.polaris_ghg_performed OWNER TO "IAM:ffdp-airflow";